### ISSUE TITLE
Client crash involving erroring packets

### ISSUE THREAD

**Issue by Bluberry-Kat** [EpicSquid/GadgetryCore#1]
not entirely sure how to reproduce, but it's happened twice now
i have two oil wells running and it wasn't happening before they were running, i suspect that may be part of it?
forge version 2772, Gadgetry version 1.0.0
[log in question](https://gist.github.com/Birgliss/b2e75f7a23f64ad181f70a810bfe362a)

edit: all i have meaningfully set up is in the following screenshot, i haven't touched the world aside from it.
![image](https://user-images.githubusercontent.com/20749209/47866142-54c80500-ddd4-11e8-9416-23af3a943bff.png)

**Comment by EpicSquid** [comment]
Yeah I think I know what it is. I'll fix it as soon as I can.

**Comment by EpicSquid** [comment]
Fixed, new release of gadgetry machines is being approved on curseforge to fix this.
