### ISSUE TITLE
Crash upon looking up JEI recipe for alloy smelter

### ISSUE THREAD

**Issue by DWX12** [EpicSquid/GadgetryCore#5]
Looked up recipe for the alloy smelter and silicon, caused Minecraft crashed. Also happens when clicking on the JEI tab for the allow smelter.

https://paste.dimdev.org/ogogelevav.mccrash

I'm using this version of JEI:
jei_1.12.2-4.13.1.224

Might be because it's the latest version of JEI.

**Comment by LumberWizard** [comment]
The issue appears to me to be caused by Fragile Glass.

**Comment by EpicSquid** [comment]
Yeah it's cause of fragile glass. It's just unfortunate we triggered it.

**Comment by DWX12** [comment]
It's been fixed and all seems to be working as intended, so far anyway.
